# Generated by Django 4.2.2 on 2023-12-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_dob_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
